// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Breed struct {
	ID        int32
	Name      string
	SpeciesID int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Pet struct {
	ID        int32
	Age       time.Time
	Name      string
	SpeciesID int32
	BreedID   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Role struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Species struct {
	ID        int32
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          int32
	FirstName   string
	LastName    string
	Email       string
	PhoneNumber string
	Password    string
	RoleID      int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
